### ISSUE TITLE
Alpha channel in TestImages.jl

### ISSUE THREAD

**Issue by ashwani-rathee** [JuliaImages/TestImages.jl#133]
I noticed a lot of activity and cleanup related work here, so just wanted to add this here. 
- Images with Alpha channel: autumn_leaves,house,jetplane,lake_gray,peppers_gray,toucan,walkbridge

What do we wish to do with that?

**Comment by johnnychen94** [comment]
If the alpha channel is trivial, i.e., `alpha.(img) == ones(size(img))`  the extra alpha channel doesn't make much sense so I would support remove it.

```julia
function has_trivial_alpha_channel(img_name)
    img = testimage(img_name)
    return eltype(img) <: TransparentColor && all(x->alpha(x) ≈ 1, img)
end

filter(has_trivial_alpha_channel, TestImages.remotefiles)
```

it gives me

```julia
7-element Vector{String}:
 "house.tif"
 "jetplane.tif"
 "lake_gray.tif"
 "morphology_test_512.tiff"
 "peppers_gray.tif"
 "sudoku.tiff"
 "walkbridge.tif"
```

But some of them has been here for quite a long time, so except for the recently added "sudoku" and "morphology_test_512", others should just stay as it is.

But actually, it is quite easy to fix on the users' side, e.g.,

```julia
img = testimage(img_name)
img = color_type(eltype(img)).(img)
```

All of them are tiff images. Just curious, @tlnagy is this an expected behavior?

**Comment by johnnychen94** [comment]
Seems nothing controversial here so I'm going to close this issue.

**Comment by tlnagy** [comment]
Didn't see this till now, but yes this is expected. These images (at least `house.tif` for sure) have embedded alpha channels even though they are all "trivial." `TiffImages.jl` tries to reproduce the on-disk color format so it loads the trivial alpha channel as well.
