### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by timholy** [JuliaImages/TestImages.jl#44]
Here's a list of files that seem to have broken links from https://testimages.juliaimages.org/:
- blobs
- cameraman
- earth_apollo17
- hela-cells
- house
- jetplane
- Sailboat on lake
- lake_gray
- lena_color_256
- ...

OK, the pattern is that anything that isn't a PNG isn't working. Perhaps https://github.com/JuliaImages/TestImages.jl/blob/a15a66607121a8a87d55d53377632805a0fae141/build.jl#L28? CC @kellertuer

**Comment by kellertuer** [comment]
Strange...ah! I found the culprit; actually, they _never_ worked. Even the previous version had https://github.com/JuliaImages/TestImages.jl/blob/a15a66607121a8a87d55d53377632805a0fae141/build.jl#L45
which printed the filename of the thumbnail (`file`) instead of the one of the images directory (`i`) into the `floc` variable (now `file_location`). But that can easily be fixed.

**Comment by timholy** [comment]
Fixed by #45
